version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "sin-simflexcloud-d1-ecs-fargate-blue-green-deployments-container"
          ContainerPort: 8080
